const {test}=require('node:test');const assert=require('node:assert/strict');
const CadenceSync=require('../app/src/main/assets/cadence-sync.js');
function fixture(rates=[.5,1,1.5,2]){const actions=[];const sync=new CadenceSync({rates:()=>rates,rate:n=>actions.push(['rate',n]),pause:()=>actions.push(['pause']),play:()=>actions.push(['play'])});sync.setEnabled(true);return{sync,actions,update(seq,rpm,t,state='tracking',confidence=1){sync.update({seq,rpm,state,confidence},t);sync.tick(t)}}}
test('60 RPM is 1x and 120 RPM selects supported rate after smoothing',()=>{const f=fixture();f.update(1,60,0);assert.deepEqual(f.actions,[['rate',1]]);for(let i=2;i<10;i++)f.update(i,120,i*1000);assert.deepEqual(f.actions.at(-1),['rate',2]);});
test('empty rates never issue rate command',()=>{const f=fixture([]);f.update(1,60,0);assert.deepEqual(f.actions,[])});
test('boundary fluctuations and 3 second hold prevent rapid rate switching',()=>{const f=fixture();f.update(1,60,0);f.update(2,90,1000);f.update(3,60,2000);assert.equal(f.actions.length,1)});
test('stop auto pauses then resumes only its own pause',()=>{const f=fixture();f.update(1,60,0);f.update(2,0,1000,'stopped');assert.deepEqual(f.actions.at(-1),['pause']);f.update(3,60,2000);assert.deepEqual(f.actions.at(-1),['play']);f.sync.manualPause();f.update(4,60,3000);assert.equal(f.actions.filter(x=>x[0]==='play').length,1)});
test('stale, low confidence and reverse sequence do not auto resume',()=>{const f=fixture();f.update(2,60,0);f.sync.tick(5001);assert.deepEqual(f.actions.at(-1),['pause']);f.update(1,120,5100);assert.deepEqual(f.actions.at(-1),['pause']);f.update(3,60,5200,'tracking',.1);assert.deepEqual(f.actions.at(-1),['pause']);f.update(4,60,6000);assert.deepEqual(f.actions.at(-1),['play'])});
test('disabling releases auto pause but preserves manual pause and new session resets sequence',()=>{const f=fixture();f.update(99,60,0);f.sync.resetConnection();f.update(1,120,6000);assert.equal(f.sync.packet.seq,1);f.sync.manualPause();f.sync.setEnabled(false);assert.equal(f.actions.some(x=>x[0]==='play'),false)});
test('unchanged actual rate is not requested again; buffering defers changes until stable playing',()=>{let actual=1,playing=true;const actions=[];const s=new CadenceSync({rates:()=>[.5,1,1.5,2],currentRate:()=>actual,canChangeRate:()=>playing,rate:n=>{actions.push(n);actual=n},pause(){},play(){}});s.setEnabled(true);s.update({seq:1,rpm:60,confidence:1,state:'tracking'},0);s.tick(0);assert.deepEqual(actions,[]);playing=false;for(let i=2;i<=10;i++){s.update({seq:i,rpm:120,confidence:1,state:'tracking'},i*1000);s.tick(i*1000)}assert.deepEqual(actions,[]);playing=true;s.tick(10000);assert.deepEqual(actions,[]);s.update({seq:11,rpm:120,confidence:1,state:'tracking'},12000);s.tick(12000);assert.deepEqual(actions,[2]);s.tick(13000);assert.deepEqual(actions,[2])});
test('unacknowledged rate request is not repeated while waiting for player',()=>{const sent=[];const s=new CadenceSync({rates:()=>[1,2],currentRate:()=>1,canChangeRate:()=>true,rate:n=>sent.push(n),pause(){},play(){}});s.setEnabled(true);for(let i=0;i<=12;i++){s.update({seq:i,rpm:120,confidence:1,state:'tracking'},i*1000);s.tick(i*1000)}assert.deepEqual(sent,[2])});
