const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
async function appFixture(){
 const {Window}=await import('happy-dom');
 const win=new Window({url:'https://com.multi0819.roadride/',settings:{enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true,disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});
 win.document.write(fs.readFileSync('app/src/main/assets/index.html','utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,''));
 const timers=[],intervals=[];const clock={now:0};win.performance.now=()=>clock.now;win.setTimeout=(callback,delay)=>{const timer={callback,delay,cleared:false};timers.push(timer);return timer};win.clearTimeout=timer=>{if(timer)timer.cleared=true};win.setInterval=callback=>{intervals.push(callback);return intervals.length};
 win.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('app/src/main/assets/routes.json','utf8'))});
 let opts,target;win.YT={Player:function(id,options){opts=options;target={playVideo(){opts.events.onStateChange({data:1})},pauseVideo(){opts.events.onStateChange({data:2})},getCurrentTime(){return 18},getAvailablePlaybackRates(){return [0.5,1,1.5]},getPlaybackRate(){return 1},setPlaybackRate(){},destroy(){},mute(){},unMute(){}};return target}};
 for(const path of ['ride-state.js','player.js','cadence-sync.js','app.js'])win.eval(fs.readFileSync('app/src/main/assets/'+path,'utf8'));
 await new Promise(resolve=>setImmediate(resolve));
 return {win,timers,clock,tick(){for(const callback of intervals)callback()},get options(){return opts},ready(){opts.events.onReady({target})},expire(){for(const t of [...timers])if(t.delay===20000&&!t.cleared)t.callback()},close(){win.happyDOM.abort()}};
}
test('player with no readiness callback exposes recovery instead of waiting forever',async()=>{const f=await appFixture();f.win.document.getElementById('heroStart').click();await new Promise(resolve=>setImmediate(resolve));f.expire();assert.equal(f.win.document.getElementById('playerNotice').hidden,false);assert.match(f.win.document.getElementById('noticeText').textContent,/인터넷/);f.close()});
test('ready player is not failed by expired startup watchdog',async()=>{const f=await appFixture();f.win.document.getElementById('heroStart').click();await new Promise(resolve=>setImmediate(resolve));f.ready();f.expire();assert.equal(f.win.document.getElementById('playerNotice').hidden,true);assert.equal(f.win.document.getElementById('status').textContent,'달리는 중');f.close()});
test('actual DOM renders eight routes and persists favorite filtering',async()=>{const f=await appFixture();const d=f.win.document;assert.equal(d.querySelectorAll('.route-card').length,8);d.querySelector('.favorite').click();d.querySelector('[data-filter="favorite"]').click();assert.equal(d.querySelectorAll('.route-card').length,1);assert.equal(d.querySelector('.favorite').getAttribute('aria-pressed'),'true');f.close()});

test('DOM controls pause timing, hide controls, save history and resume at saved position',async()=>{const f=await appFixture();const d=f.win.document;d.getElementById('heroStart').click();await new Promise(resolve=>setImmediate(resolve));f.ready();f.clock.now=3000;f.tick();assert.equal(d.getElementById('timer').textContent,'00:03');d.getElementById('playBtn').click();f.clock.now=10000;f.tick();assert.equal(d.getElementById('timer').textContent,'00:03');d.getElementById('immersiveBtn').click();assert.equal(d.getElementById('ride').classList.contains('immersive'),true);d.getElementById('showControls').click();assert.equal(d.getElementById('ride').classList.contains('immersive'),false);d.getElementById('endBtn').click();assert.equal(d.querySelectorAll('.history-row').length,1);assert.equal(d.getElementById('resumeBtn').hidden,false);d.getElementById('resumeBtn').click();await new Promise(resolve=>setImmediate(resolve));assert.equal(f.options.playerVars.start,18);f.close()});
test('RPM controls pause on disconnect, preserve manual pause and restore manual rates',async()=>{const f=await appFixture();const d=f.win.document;assert.ok(d.getElementById('measureBtn'));assert.ok(d.getElementById('connectBtn'));d.getElementById('heroStart').click();await new Promise(resolve=>setImmediate(resolve));f.ready();f.win.onCadenceStatus('connected');f.win.onCadencePacket({seq:1,rpm:60,confidence:1,state:'tracking'});const auto=d.getElementById('cadenceAuto');auto.checked=true;auto.dispatchEvent(new f.win.Event('change'));f.win.onCadenceStatus('disconnected');assert.equal(d.getElementById('status').textContent,'일시정지');f.win.onCadenceStatus('connected');f.win.onCadencePacket({seq:1,rpm:60,confidence:1,state:'tracking'});assert.equal(d.getElementById('status').textContent,'달리는 중');d.getElementById('playBtn').click();f.win.onCadencePacket({seq:2,rpm:90,confidence:1,state:'tracking'});assert.equal(d.getElementById('status').textContent,'일시정지');auto.checked=false;auto.dispatchEvent(new f.win.Event('change'));assert.equal(d.getElementById('rate').disabled,false);f.close()});
test('YouTube own play after own pause restores RPM sync and disconnect protection',async()=>{const f=await appFixture();const d=f.win.document;d.getElementById('heroStart').click();await new Promise(resolve=>setImmediate(resolve));f.ready();f.win.onCadenceStatus('connected');f.win.onCadencePacket({seq:1,rpm:60,confidence:1,state:'tracking'});const auto=d.getElementById('cadenceAuto');auto.checked=true;auto.dispatchEvent(new f.win.Event('change'));f.options.events.onStateChange({data:2});f.options.events.onStateChange({data:1});f.win.onCadenceStatus('disconnected');assert.equal(d.getElementById('status').textContent,'일시정지');f.close()});
